/**
 * markdownExporter.ts
 *
 * Generates Markdown export files from a Presentation object.
 * All content comes from slides — no content is invented here.
 */

import type { Presentation } from '@/types'

/**
 * Generate outline.md — a structured overview of all slides.
 */
export function generateOutlineMd(presentation: Presentation): string {
  const lines: string[] = [
    `# ${presentation.title}`,
    '',
    `**Audience:** ${presentation.audience}`,
    `**Tone:** ${presentation.tone}`,
    `**Design:** ${presentation.designPlot}`,
    `**Slides:** ${presentation.slideCount}`,
    `**Created:** ${new Date(presentation.createdAt).toLocaleDateString()}`,
    '',
    '---',
    '',
  ]

  for (const slide of presentation.slides) {
    lines.push(`## Slide ${slide.slideNumber}: ${slide.title}`)
    if (slide.mainBullets.length > 0) {
      for (const bullet of slide.mainBullets) {
        lines.push(`- ${bullet}`)
      }
    } else {
      lines.push('_(Title slide — no bullets)_')
    }
    lines.push('')
  }

  return lines.join('\n')
}

/**
 * Generate slides.md — each slide as a fenced section.
 */
export function generateSlidesMd(presentation: Presentation): string {
  const sections: string[] = [
    `<!-- Presentation: ${presentation.title} -->`,
    `<!-- Design: ${presentation.designPlot} | Audience: ${presentation.audience} -->`,
    `<!-- Generated by Presentation Creator Agent — all content from user's lesson -->`,
    '',
  ]

  for (const slide of presentation.slides) {
    sections.push('---')
    sections.push(`slide: ${slide.slideNumber}`)
    sections.push(`title: "${slide.title}"`)
    sections.push('---')
    sections.push('')
    sections.push(`# ${slide.title}`)
    sections.push('')

    if (slide.mainBullets.length > 0) {
      for (const bullet of slide.mainBullets) {
        sections.push(`- ${bullet}`)
      }
      sections.push('')
    }

    if (slide.speakerNotes) {
      sections.push(`> **Speaker notes:** ${slide.speakerNotes}`)
      sections.push('')
    }

    if (slide.designNotes) {
      sections.push(`> **Design:** ${slide.designNotes}`)
      sections.push('')
    }
  }

  sections.push('---')
  return sections.join('\n')
}

/**
 * Generate design-notes.md — design specifications for each slide.
 */
export function generateDesignNotesMd(presentation: Presentation): string {
  const lines: string[] = [
    `# Design Notes — ${presentation.title}`,
    '',
    `**Design Plot:** ${presentation.designPlot}`,
    `**Output Style:** ${presentation.outputStyle}`,
    '',
    '---',
    '',
    '## Per-Slide Design Specifications',
    '',
  ]

  for (const slide of presentation.slides) {
    lines.push(`### Slide ${slide.slideNumber}: ${slide.title}`)
    lines.push('')
    lines.push(`**Layout:** ${slide.layoutSuggestion}`)
    lines.push(`**Background:** ${slide.backgroundSuggestion}`)
    lines.push(`**Visual Direction:** ${slide.visualDirection}`)
    lines.push(`**Design Notes:** ${slide.designNotes}`)
    lines.push('')
  }

  return lines.join('\n')
}
